name: Reusable Workflow

on:
  call-reusable-workflow:
  uses: ./.github/workflows/reusable-workflow.yml
  with:
    node: 14

jobs:
  build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}"
